# Generated by Django 5.0 on 2023-12-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_author_alter_entry_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
