version: '3.0'
services:
  web:
    image: odoo:16.0
    env_file: myenvfile.env
    depends_on:
      - db
    ports:
      - "8066:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
  
  db:
    image: postgres:15
    env_file: myenvfile.env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  
  pgadmin4:
    image: dpage/pgadmin4:4.25
    environment: 
        PGADMIN_DEFAULT_EMAIL: shadmin@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin1234
        PGADMIN_LISTEN_PORT: 80
    ports:
        - "8888:80"
    volumes:
        - pgadmin4:/var/lib/pgadmin

volumes:
  odoo-web-data:
  odoo-db-data:
  pgadmin4:

